version: "3.9"

services:
  generator:
    image: python:3.10
    volumes:
      - ./data:/data
      - ./generator:/app
      - ./configs:/configs
    working_dir: /app
    command: python data_generator.py

  spark:
    build: ./docker
    volumes:
      - ./data:/data
      - ./spark:/app/spark
      - ./configs:/app/configs
    command: spark-submit /app/spark/spark_streaming.py
